"""
strategies/base_strategy.py
Abstract base class for all trading strategies.
"""
from __future__ import annotations

import abc
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

import pandas as pd

logger = logging.getLogger(__name__)


class SignalType(str, Enum):
    BUY   = "BUY"
    SELL  = "SELL"
    HOLD  = "HOLD"
    SHORT = "SHORT"
    COVER = "COVER"


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    date:       pd.Timestamp
    ticker:     str
    signal:     SignalType
    strength:   float = 1.0        # 0-1 normalised confidence / size fraction
    price:      Optional[float] = None
    stop_loss:  Optional[float] = None
    take_profit:Optional[float] = None
    meta:       Dict[str, Any] = field(default_factory=dict)

    def is_entry(self) -> bool:
        return self.signal in (SignalType.BUY, SignalType.SHORT)

    def is_exit(self) -> bool:
        return self.signal in (SignalType.SELL, SignalType.COVER)


class BaseStrategy(abc.ABC):
    """
    Abstract base class every strategy must implement.

    Lifecycle
    ---------
    1. __init__ stores parameters
    2. prepare(data) pre-computes indicators on the full history
    3. generate_signals(data) returns a list of Signal objects

    The backtester calls prepare() once, then steps through dates
    calling generate_signals() for the current bar.
    """

    name: str = "BaseStrategy"

    def __init__(self, params: Optional[Dict[str, Any]] = None) -> None:
        self.params: Dict[str, Any] = params or {}
        self._indicators: Dict[str, pd.DataFrame] = {}
        self.logger = logging.getLogger(self.__class__.__name__)

    # ──────────────────────────────────────────
    # Required overrides
    # ──────────────────────────────────────────

    @abc.abstractmethod
    def prepare(self, data: Dict[str, pd.DataFrame]) -> None:
        """
        Pre-compute indicators from the full OHLCV history.
        Called once before the backtest loop begins.

        Parameters
        ----------
        data : {ticker: ohlcv_df} mapping
        """
        ...

    @abc.abstractmethod
    def generate_signals(
        self,
        date: pd.Timestamp,
        data: Dict[str, pd.DataFrame],
        portfolio_state: Optional[Dict] = None,
    ) -> List[Signal]:
        """
        Generate trading signals for *date*.

        Parameters
        ----------
        date           : current bar date
        data           : full OHLCV history up to and including *date*
        portfolio_state: current portfolio state (positions, cash, etc.)

        Returns
        -------
        List of Signal objects (may be empty)
        """
        ...

    # ──────────────────────────────────────────
    # Optional overrides
    # ──────────────────────────────────────────

    def on_fill(self, order, fill) -> None:
        """Called when an order is filled. Override for bookkeeping."""
        pass

    def on_bar(self, date: pd.Timestamp, data: Dict[str, pd.DataFrame]) -> None:
        """Called at the start of each bar (before signal generation)."""
        pass

    # ──────────────────────────────────────────
    # Helpers
    # ──────────────────────────────────────────

    def get_param(self, key: str, default: Any = None) -> Any:
        return self.params.get(key, default)

    def set_param(self, key: str, value: Any) -> None:
        self.params[key] = value

    @staticmethod
    def _latest_bar(df: pd.DataFrame, date: pd.Timestamp) -> Optional[pd.Series]:
        """Return the last row of *df* up to and including *date*."""
        sliced = df.loc[:date]
        return sliced.iloc[-1] if not sliced.empty else None

    @staticmethod
    def _n_bars_ago(
        df: pd.DataFrame,
        date: pd.Timestamp,
        n: int,
    ) -> Optional[pd.Series]:
        """Return the row *n* bars before *date*."""
        sliced = df.loc[:date]
        if len(sliced) <= n:
            return None
        return sliced.iloc[-(n + 1)]

    def _indicator(self, ticker: str) -> Optional[pd.DataFrame]:
        return self._indicators.get(ticker)

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(params={self.params})"
